"""empty message

Revision ID: 02e806641431
Revises: 09cd6c44ce2c
Create Date: 2020-03-24 20:16:40.489766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e806641431'
down_revision = '09cd6c44ce2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('temp', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
