"""okay okay fine i'll make this actually descriptive: added pet_image_url listing field

Revision ID: 75dd7eaac932
Revises: f2c1bed97f39
Create Date: 2020-04-22 02:56:53.702161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dd7eaac932'
down_revision = 'f2c1bed97f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('pet_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'pet_image_url')
    # ### end Alembic commands ###
