"""Added longitude/latitude

Revision ID: 7b4c43ed2b1a
Revises: 75dd7eaac932
Create Date: 2020-04-29 03:04:55.691055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4c43ed2b1a'
down_revision = '75dd7eaac932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('lat', sa.Numeric(), nullable=False))
    op.add_column('listing', sa.Column('lng', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'lng')
    op.drop_column('listing', 'lat')
    # ### end Alembic commands ###
