"""Added address raw string

Revision ID: 97518663f724
Revises: daf421fcf953
Create Date: 2020-04-29 03:57:57.722791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97518663f724'
down_revision = 'daf421fcf953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('address_str', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'address_str')
    # ### end Alembic commands ###
