"""Loosened uniqueness restriction on phone numbers

Revision ID: d582f48cff3f
Revises: 97518663f724
Create Date: 2020-05-02 00:19:16.424043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd582f48cff3f'
down_revision = '97518663f724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_phone_number_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_phone_number_key', 'user', ['phone_number'])
    # ### end Alembic commands ###
