"""Added address_id for Algolia queries

Revision ID: daf421fcf953
Revises: 7b4c43ed2b1a
Create Date: 2020-04-29 03:45:15.801947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf421fcf953'
down_revision = '7b4c43ed2b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('address_id', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'address_id')
    # ### end Alembic commands ###
